[buildPlans.bmono]
family = "Bmono"
spacing = "fontconfig-mono"
serifs = "sans"
no-cv-ss = false
export-glyph-names = true

  [buildPlans.bmono.variants]
  inherits = "ss20"

    [buildPlans.bmono.variants.design]
    capital-g = "toothless-rounded-serifless-hooked"
    l = "tailed-serifed"
    zero = "dotted"
    eight = "two-circles"
    asterisk = "penta-low"
    caret = "low"
    paren = "large-contour"
    dollar = "open"
    cent = "open"
    percent = "rings-continuous-slash"
    bar = "force-upright"

  [buildPlans.bmono.ligations]
  inherits = "dlig"
  disables = [ "logic" ]

[buildPlans.bmono.widths.normal]
shape = 600
menu = 5
css = "normal"
